version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=https://iqqtecondicfclncwjio.supabase.co
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxcXRlY29uZGljZmNsbmN3amlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNzM3OTMsImV4cCI6MjA1Njg0OTc5M30.c83RWUSzxgfJwcM6t44vWQqjgjlVu3PhtFho4X9bzfo

networks:
  survey-network:
    driver: bridge 