version: '3.8'

services:
  survey-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: survey-app
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - survey-network

networks:
  survey-network:
    driver: bridge 